# Generated by Django 2.1.4 on 2019-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190506_1016'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='food_ordered',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
