# Generated by Django 2.2.1 on 2019-06-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190506_1016'),
        ('products', '0004_auto_20190526_1436'),
    ]

    operations = [
    ]
